export default class BoardManager {

	constructor() {}

	generateBoard(height: number, width: number) {
		return [
			[
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
			],
			[
				{isOpen: false},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: false},
			],
			[
				{isOpen: false},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: false},
			],
			[
				{isOpen: false},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: false},
			],
			[
				{isOpen: false},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: false},
			],
			[
				{isOpen: false},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: false},
			],
			[
				{isOpen: false},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: false},
			],
			[
				{isOpen: false},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: true},
				{isOpen: false},
			],
			[
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
				{isOpen: false},
			],
		]
	}
}